on: [push]

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: deploy file
        uses: shimataro/ssh-key-action@v2
        with:
          username: 'root'
          server: 178.62.102.194
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} 
          local_path: './*'
          remote_path: '/odoo/custom'
          args: '-o ConnectTimeout=5'
